pool:
  vmImage: "ubuntu-latest"

jobs:
- job: build
  displayName: Build
  steps:
  - checkout: self
    persistCredentials: true

  - task: NodeTool@0
    inputs:
      versionSpec: 10.x
    displayName: Install node.js

  - script: yarn install
    displayName: Install dependencies

  - script: yarn run lint
    displayName: Run linters

  - script: yarn run build
    displayName: Build

  - script: yarn run coverage
    displayName: Run tests

  - script: |
      wget -q https://github.com/github/hub/releases/download/v2.13.0/hub-linux-amd64-2.13.0.tgz
      tar xfz hub-linux-amd64-2.13.0.tgz
      export PATH=$PATH:$(pwd)/hub-linux-amd64-2.13.0/bin

      git config user.name "Azure Pipelines Automation"
      ./pipelines/release.sh
    condition: and(succeeded(), eq(variables['release'], 'true'))
    displayName: Release on GitHub
    env:
      GITHUB_TOKEN: $(github_token)
