pool:
  vmImage: "ubuntu-latest"

jobs:
- job: qa
  displayName: QA
  steps:
  - script: yarn install
    displayName: Install dependencies

  - script: yarn run lint
    displayName: Run linters

  - script: yarn run build
    displayName: Build

  - script: yarn run coverage
    displayName: Run tests
