trigger: none
pr: none

pool:
  vmImage: "ubuntu-latest"

jobs:
  - job: release
    displayName: Release
    steps:
      - checkout: self
        persistCredentials: true

      - template: qa-steps.yml

      - script: |
          wget -q https://github.com/github/hub/releases/download/v2.13.0/hub-linux-amd64-2.13.0.tgz
          tar xfz hub-linux-amd64-2.13.0.tgz
          export PATH=$PATH:$(pwd)/hub-linux-amd64-2.13.0/bin

          git config user.name "Azure Pipelines Automation"
          ./pipelines/release.sh
        displayName: Release on GitHub
        env:
          GITHUB_TOKEN: $(github_token)
