trigger: none
pr: none

pool:
  vmImage: "ubuntu-latest"

jobs:
  - job: release
    displayName: Release
    steps:
      - checkout: self
        persistCredentials: true

      - template: qa-steps.yml

      - script: |
          wget -q -O hub-linux-amd64.tgz https://github.com/github/hub/releases/download/v2.13.0/hub-linux-amd64-2.13.0.tgz
          tar -xf hub-linux-amd64.tgz && sudo mv ./hub-linux-amd64-*/bin/hub /usr/local/bin

          git config user.name "Azure Pipelines Automation"
          ./pipelines/release.sh
        displayName: Release on GitHub
        env:
          GITHUB_TOKEN: $(github_token)
